apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx
    labels: 
        app: nginx
        type: front-end
spec:
    template:
        metadata:
           name: nginx
           labels: 
             app: nginx
             type: pod 
        spec:
           containers: 
           - name: nginx-container
             image: nginx
    replicas: 3